nbMissionsMax: 5
dossierLogs: 'logs'
nbLogsMax: 1

graphe:
  0:
    1: 2
  1:
    2: 1
    0: 2
  2:
    1: 1

noeudsGare:
  - 0
  - 1
  - 2

requetes:
  0: [2, 0, 10]      # Le wagon 0 doit atteindre le noeud 2 entre l'instant 0 et 10

motrices:
  0: 0
  1: 2

wagons:
  0: 1