# --------------------------------------------------------------
# PARAMETRES GENERAUX
# --------------------------------------------------------------
# Dossier dans lequel sont exportés les logs
dossierLogs: 'logs'

# Nombre maximum de logs à garder dans le dossier logs
nbLogsMax: 1


# --------------------------------------------------------------
# PARAMETRES DE L'ALGORITHME GENETIQUE
# --------------------------------------------------------------
# Nombre de générations à calculer. Plus la valeur est grande, plus l'algorithme pourra explorer de solutions. 
nbGenerations: 100

# Nombre de solutions générées à chaque génération.
taillePopulation: 150

# Probabilité de croisement entre les solutions. Choisir une valeur entre 0 et 1.
cxpb: 0.85

# Probabilité de mutation des solutions. Choisir une valeur entre 0 et 1.
mutpb: 0.2


# --------------------------------------------------------------
# PARAMETRES DU PROBLEME
# --------------------------------------------------------------
# Nombre d'instants maximum simulés
horizonTemporel: 500

# Coût d'une unité de temps d'avance ou de retard sur une requête
coutUnitaireRequetes: 1

# Coût logistique de l'attelage ou du désattelage d'un wagon 
coutUnitaireAttelage: 1

# Coût logistique du déplacement d'une motrice pendant une unité de temps
coutUnitaireDeplacement: 1