# --------------------------------------------------------------
# PARAMETRES GENERAUX
# --------------------------------------------------------------
# Dossier dans lequel sont exportés les logs
dossierLogs: 'logs'

# Nombre maximum de logs à garder dans le dossier logs
nbLogsMax: 1


# --------------------------------------------------------------
# PARAMETRES DE L'ALGORITHME GENETIQUE
# --------------------------------------------------------------
# Nombre de générations à calculer. Plus la valeur est grande, plus l'algorithme pourra explorer de solutions. 
nbGenerations: 500

# Nombre de solutions générées à chaque génération.
taillePopulation: 150

# Probabilité de croisement entre les solutions. Choisir une valeur entre 0 et 1.
cxpb: 0.85

# Probabilité de mutation des solutions. Choisir une valeur entre 0 et 1.
mutpb: 0.2


# --------------------------------------------------------------
# PARAMETRES DU PROBLEME
# --------------------------------------------------------------
# Nombre d'instants maximum simulés
horizonTemporel: 500

# Coût d'une unité de temps d'avance ou de retard sur une requête
coutUnitaireRequetes: 1

# Coût logistique de l'attelage ou du désattelage d'un wagon 
coutUnitaireAttelage: 1

# Coût logistique du déplacement d'une motrice pendant une unité de temps
coutUnitaireDeplacement: 1


# --------------------------------------------------------------
# STRUCTURE DU PROBLEME
# --------------------------------------------------------------
graphe:
  0: {1: 2, 5: 4}
  1: {0: 2, 2: 2, 6: 3}
  2: {1: 2, 3: 1}
  3: {2: 1, 4: 2, 8: 5}
  4: {3: 2, 9: 3}
  5: {0: 4, 6: 1, 10: 6}
  6: {1: 3, 5: 1, 7: 2}
  7: {6: 2, 8: 1, 11: 4}
  8: {3: 5, 7: 1, 9: 2}
  9: {4: 3, 8: 2, 13: 3}
  10: {5: 6, 11: 1}
  11: {7: 4, 10: 1, 12: 3}
  12: {11: 3, 13: 1}
  13: {9: 3, 12: 1, 14: 2}
  14: {13: 2}

noeudsGare:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14

requetes:
  0:
    - [4, 8, 5, 15]
    - [2, 14, 25, 35]
  1:
    - [5, 0, 10, 20]
  2:
    - [3, 6, 0, 10]
    - [6, 10, 15, 25]
  3:
    - [8, 2, 30, 40]
  4:
    - [1, 12, 12, 22]
  5:
    - [9, 14, 20, 30]
  6:
    - [0, 4, 8, 18]
  7:
    - [7, 2, 5, 15]
  8:
    - [2, 10, 16, 26]
  9:
    - [6, 0, 20, 30]

motrices:
  0: 0
  1: 3
  2: 6
  3: 10
  4: 13

wagons:
  0: 1
  1: 3
  2: 5
  3: 2
  4: 4
  5: 6
  6: 7
  7: 9
  8: 11
  9: 12