nbMissionsMax: 5
dossierLogs: 'logs'
nbLogsMax: 1

graphe:
  0:
    1: 1
  1:
    0: 1
    2: 1
    3: 1
  2:
    1: 1
    3: 3
  3:
    1: 1
    2: 3
    4: 2
  4:
    3: 2

noeudsGare:
  - 0
  - 2
  - 3
  - 4

requetes:
  0: 
    - [3, 5, 6, 10]
    - [2, 2, 1, 10]
  1:
    - [4, 1, 7, 10]

motrices:
  0: 0
  1: 4

wagons:
  0: 2
  1: 3