# --------------------------------------------------------------
# PARAMETRES GENERAUX
# --------------------------------------------------------------
# Dossier dans lequel sont exportés les logs
dossierLogs: 'logs'

# Nombre maximum de logs à garder dans le dossier logs
nbLogsMax: 1


# --------------------------------------------------------------
# PARAMETRES DE L'ALGORITHME GENETIQUE
# --------------------------------------------------------------
# Nombre de générations à calculer. Plus la valeur est grande, plus l'algorithme pourra explorer de solutions. 
nbGenerations: 50

# Nombre de solutions générées à chaque génération.
taillePopulation: 150

# Probabilité de croisement entre les solutions. Choisir une valeur entre 0 et 1.
cxpb: 0.85

# Probabilité de mutation des solutions. Choisir une valeur entre 0 et 1.
mutpb: 0.2


# --------------------------------------------------------------
# STRUCTURE DU PROBLEME
# --------------------------------------------------------------
# Nombre de missions maximum à la génération des solutions
nbMissionsMax: 5

# Nombre d'instants maximum simulés
horizonTemporel: 500


graphe:
  0: {1: 5, 2: 10}
  1: {0: 5}
  2: {0: 10, 3: 1}
  3: {2: 1}

noeudsGare:
  - 0
  - 1
  - 2
  - 3

requetes:
  0:
    - [2, 1, 20, 30]
  1:
    - [0, 1, 20, 30]

motrices:
  0: 3
  1: 1

wagons:
  0: 3
  1: 1
